name: Scan Golang project
on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    name: Install CRC
    steps:
    - name: Download & Install
      run: |
        # curl -sSLf \
        curl https://mirror.openshift.com/pub/openshift-v4/clients/kam/latest/kam-windows-amd64.zip --output kam-windows-amd64.zip
        unzip kam-windows-amd64.zip -d ./
        # curl https://mirror.openshift.com/pub/openshift-v4/clients/crc/1.31.2/crc-windows-installer.zip
        # curl https://mirror.openshift.com/pub/openshift-v4/clients/kam/latest/kam-windows-amd64.zip
        # unzip kam-windows-amd64.zip
        ls
        # msiexec /i "E:\crc-windows-amd64.msi
